//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIKitTutorials.Classes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner
    {
        public int idOwner { get; set; }
        public Nullable<int> idPlace { get; set; }
        public Nullable<int> idClient { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Place Place { get; set; }
    }
}
